#!/bin/bash
cl="\033c"
normal="\u001b[0m"
green="\u001b[48;1;32m"
red="\u001b[48;1;31m"
yell="\u001b[48;1;33m"

echo -e "$cl$yell""-> ""$green""Updating .... $normal"

apt update && apt upgrade
echo -ne "$cl$yell""-> ""$green""Setup termux storage? $red (Y/n) $normal: "
read ins
if [ "$ins" = "Y" ]; then
termux-setup-storage
fi
echo -e "$yell""-> ""$green""installing nessasary packages...$normal"
apt install python nodejs clang nmap yarn micro file php
echo -e "$yell""-> ""$green""Installed some nessasary files.. $normal"
echo ""
echo -ne "$cl$yell""-> ""$green""Install heroku? $red(Y/n) $normal: "
read ins
if [ "$ins" = "Y" ]; then
npm i --location=global heroku
echo -ne "$cl$yell""-> ""$green""Login to heroku? $red (Y/n)$normal : "
read ins
if [ "$ins" = "Y" ]; then
heroku auth:login
fi
fi
echo -ne "$cl$yell""-> ""$green""Install git?$red (Y/n) $normal: "
read ins
if [ "$ins" = "Y" ]; then
apt install git
echo -ne "$yell""-> ""$green""Enter github username: $normal"
read username
echo -ne "$yell""-> ""$green""Enter github email: $normal"
read email
echo "$yell""-> ""$green""Configuring github   $normal"
git config --global user.name $username
git config --global user.email $email
git config --list
echo "$yell""-> ""$green""Configured github$normal"
echo -ne "$cl$yell""-> ""$green""Install gh (git)?$red (Y/n)$normal : "
read ins
if [ "$ins" = "Y" ]; then
apt install gh
echo -e "$yell""-> ""$green""Setup gh... $normal"
echo ""
gh auth login
fi
fi
echo -e "$cl$yell""-> ""$green""Termux Setup Completed"
echo -e "$yell""-> ""$red""Go on...$normal"
